function [png] = robot2_pn_pdf()

png.PN_name = 'Model of the second robot';
png.set_of_Ps = {'pRobot2','pWheels2','pThongs','plThongOpen','prThongOpen','prThongClose','plThongClose',};
png.set_of_Ts={'tpRobot2_pWheels2','tpRobot2_pThongs','tpThongs_prThongClose','tpThongs_plThongClose','tpThongs_plThongOpen','tpThongs_prThongOpen'};
png.set_of_As={'pRobot2','tpRobot2_pWheels2',1,'tpRobot2_pWheels2','pWheels2',1,...
               'pRobot2','tpRobot2_pThongs',1,'tpRobot2_pThongs','pThongs',1,...
               'pThongs','tpThongs_prThongClose',1,'tpThongs_prThongClose','prThongClose',1,...
               'pThongs','tpThongs_plThongClose',1,'tpThongs_plThongClose','plThongClose',1,...
               'pThongs','tpThongs_plThongOpen',1,'plThongClose','tpThongs_plThongOpen',1,'tpThongs_plThongOpen','plThongOpen',1,...
               'pThongs','tpThongs_prThongOpen',1,'prThongClose','tpThongs_prThongOpen',1,'tpThongs_prThongOpen','prThongOpen',1};    
png.set_of_Is={'prThongClose','tpThongs_prThongClose',1,...
               'plThongClose','tpThongs_plThongClose',1};

end


