function [png] = robot2_pn_pdf()

png.PN_name = 'Model of the second robot';
png.set_of_Ps = {'pRobot2','pWheels2','pThongs','plThongOpen','prThongOpen','prThongClose','plThongClose','pGoto2','pReady2','pCaptor2'};

png.set_of_Ts={'tpRobot2_pWheels2','tpRobot2_pThongs','tpThongs_prThongClose','tpThongs_plThongClose','tpThongs_plThongOpen','tpThongs_prThongOpen','tGoto2','tMoving2','tReStart2','tStop2','tCaptor2','tFinish2'};

png.set_of_As={'pRobot2','tpRobot2_pWheels2',1,'tpRobot2_pWheels2','pWheels2',1,...
               'pRobot2','tpRobot2_pThongs',1,'tpRobot2_pThongs','pThongs',1,...
               'pThongs','tpThongs_prThongClose',1,'tpThongs_prThongClose','prThongClose',1,...
               'pThongs','tpThongs_plThongClose',1,'tpThongs_plThongClose','plThongClose',1,...
               'pThongs','tpThongs_plThongOpen',1,'plThongClose','tpThongs_plThongOpen',1,'tpThongs_plThongOpen','plThongOpen',1,...
               'pThongs','tpThongs_prThongOpen',1,'prThongClose','tpThongs_prThongOpen',1,'tpThongs_prThongOpen','prThongOpen',1,...
               'pWheels2','tGoto2',1,'tGoto2','pGoto2',1,...
               'pGoto2','tMoving2',1,'pReady2','tMoving2',1,'tMoving2','pGoto2',1,...
               'pGoto2','tFinish2',1,...
               'tCaptor2','pCaptor2',1,...
               'pCaptor2','tReStart2',1,'tReStart2','pReady2',1,...
               'pReady2','tStop2',1,'pCaptor2','tStop2',1};    

png.set_of_Is={'prThongClose','tpThongs_prThongClose',1,...
               'plThongClose','tpThongs_plThongClose',1};

end


