set_of_Ps = {'py1', 'pyRamp', 'py2', 'pyBasket', ... %<- starting area, yellow player
    'pmc1', 'pmc2', 'pmc3', 'pyTower', 'pyc1', 'pyc2', 'pc2Tower', ...
    'pslot2', 'pslot4', 'pslot5', 'psba2', 'psba4', 'pbba2', ...
    'pslot2-1', 'pslot2-2', 'pslot2-3'}; %<- arena places (yellow player's half)
set_of_Ts = {'ty1', 'ty2', ... %<- starting area, yellow player
    'tyTower', 'tyTower-mc1', 'tyTower-slot4', ...
    'tmc1-mc3', 'tmc1-sba2', ...
    'tslot4-slot5', ...
    'tslot5-sba4', 'tslot5-mc3', ...
    'tsba4-bba2', 'tsba4-yc2', ...
    'tbba2', 'tbba2-c2Tower', 'tbba2-yc2', 'tbba2-sba2', ...
    'tyc2-mc2', ...
    'tmc3-sba2', 'tmc3-mc2', 'tmc3-slot2', ...
    'tsba2-slot4', 'tsba2-mc2', 'tsba2-yc1', 'tsba2-slot2', 'tsba2-c2Tower', ...
    'tmc2-slot2', 'tmc2-c2Tower', ...
    'tc2Tower', ...
    'tslot2-c2Tower', 'tslot2-yc1', 'tslot2-1', 'tslot2-2', 'tslot2-3', ...
    'tyc1-ybasket'};

place={"pyTower","pymc1","pysba2"}
matrix=[0 1 0;1 0 1; 0 0 1]
set_of_As={}
for i =1:length(place)
    for j=1:length(place)
        if(matrix(i,j)>0)
            l=length(set_of_As)
			%set_of_Ts = {'t'+place(i)+'-'+place(j)} }
			set_of_As{1,(l+1)}=place(i)
            set_of_As{1,(l+2)}=place(j)
            set_of_As{1,(l+3)}=strcat('t',place(i),'-',place(j))
            set_of_As{1,(l+4)}=matrix(i,j)
        end
    end
end

for i=1:length(set_of_As)
    set_of_As{1,i}
end